apiVersion: v1
kind: Service
metadata:
  namespace: todo
  name: web-service
  labels:
    name: web
    app: todoapp
spec:
  selector:
    name: web 
  type: NodePort
  ports:
   - name: http
     port: 3000
     targetPort: 3000
     nodePort: 30002
     protocol: TCP